identifier: com.busybox11.ciderjams
name: Cider Jams
description: A simple listening session sharing plugin
author: busybox11
repo: https://github.com/busybox11/ciderjams
entry:
  "plugin.js":
    type: main